monolog:
    handlers:
        main:
            type: stream
            path: php://stdout
            channels: ["!event"]
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]